language: python

cache: pip

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

env:
  global:
    - TEST_DIR=/tmp/_altair/

before_install:
  - pip install pip --upgrade;
  - pip install -U pytest;

install:
  - pip install -e .[dev];

script:
  - mkdir -p $TEST_DIR
  - cd $TEST_DIR && python -m pytest --pyargs --doctest-modules altair;
