name: docbuild

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [ 'html', 'doctest' ]
    name: ${{ matrix.build-type }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
        pip install altair_saver
        pip install -r doc/requirements.txt
    - name: Run docbuild
      run: |
        cd doc && make ${{ matrix.build-type }}

        